### ISSUE TITLE
Crowdstrike Device Lookup Saved Search has wrong Mac Address Path

### ISSUE THREAD

**Issue by PaddlingCode** [ZachChristensen28/SA-CrowdstrikeDevices#30]
https://github.com/ZachChristensen28/SA-CrowdstrikeDevices/blob/4133874664e5ec49d192a229007ae878f1beb756/src/SA-CrowdstrikeDevices/default/savedsearches.conf#L15

Needs to be changed to:

`| dedup falcon_device.device_id falcon_device.mac_address \`

**Comment by noodletoad** [comment]
I have the same issue running the latest TA (3.1.1)

**Comment by ZachChristensen28** [comment]
Thanks for pointing this out. I will get a fix out shortly.
